// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDSr6ZBmZONlwG1SjyhiXd1DB6tb3tjMg',
    appId: '1:263905072020:web:a39a5ab6920816007c3581',
    messagingSenderId: '263905072020',
    projectId: 'pettahfinds-75075',
    authDomain: 'pettahfinds-75075.firebaseapp.com',
    storageBucket: 'pettahfinds-75075.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHZhkY9YrRBhaoS5fjUl5pcP4t4TvMN8',
    appId: '1:263905072020:android:8e7314414fee06c47c3581',
    messagingSenderId: '263905072020',
    projectId: 'pettahfinds-75075',
    storageBucket: 'pettahfinds-75075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACy0k9Q3ZRJj5PUQB68nC5FyAvFgbIU88',
    appId: '1:263905072020:ios:866f9c8043f5aa2e7c3581',
    messagingSenderId: '263905072020',
    projectId: 'pettahfinds-75075',
    storageBucket: 'pettahfinds-75075.firebasestorage.app',
    androidClientId: '263905072020-v7lqqisasukaaj48k1g1rp7i4v93secd.apps.googleusercontent.com',
    iosClientId: '263905072020-rhmdc4qm4f2gqe27hmcmjqaogbgk5qp5.apps.googleusercontent.com',
    iosBundleId: 'com.petafinds.petafinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACy0k9Q3ZRJj5PUQB68nC5FyAvFgbIU88',
    appId: '1:263905072020:ios:866f9c8043f5aa2e7c3581',
    messagingSenderId: '263905072020',
    projectId: 'pettahfinds-75075',
    storageBucket: 'pettahfinds-75075.firebasestorage.app',
    androidClientId: '263905072020-v7lqqisasukaaj48k1g1rp7i4v93secd.apps.googleusercontent.com',
    iosClientId: '263905072020-rhmdc4qm4f2gqe27hmcmjqaogbgk5qp5.apps.googleusercontent.com',
    iosBundleId: 'com.petafinds.petafinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDSr6ZBmZONlwG1SjyhiXd1DB6tb3tjMg',
    appId: '1:263905072020:web:d628e738f36ec7e17c3581',
    messagingSenderId: '263905072020',
    projectId: 'pettahfinds-75075',
    authDomain: 'pettahfinds-75075.firebaseapp.com',
    storageBucket: 'pettahfinds-75075.firebasestorage.app',
  );
}
